apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 526869692095.dkr.ecr.us-east-1.amazonaws.com/mysql_db
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "hj"
    ports:
    - containerPort: 3306