apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: employees
spec:
  containers:
  - name: web
    image: 526869692095.dkr.ecr.us-east-1.amazonaws.com/webapp
    env:
    - name: DBHOST
      value: "mysql.mysql.svc.cluster.local"
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "hj"
    ports:
    - containerPort: 8080