apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 526869692095.dkr.ecr.us-east-1.amazonaws.com/mysql_db:v0.1
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "hj"
        ports:
        - containerPort: 3306